name: mini-project-income
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.18
  - pandas>=1.0
  - matplotlib>=3.2
  - seaborn>=0.11
  - scikit-learn>=1.0
  - mlflow>=2.0
  - scipy>=1.5
  - joblib>=1.0
  - notebook
  - ipykernel
  - pip
